import type { Metadata } from 'next';
import '@/app/globals.css';
import Header from '@/components/Header';

import { ThemeProvider } from '../hooks/ThemeContext';

export const metadata: Metadata = {
  title: 'OPBS Companion',
  description: 'Generated by create next app',
  icons: {
    icon: '/images/.png'
  }
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <div className="min-h-screen flex flex-col">
            <Header />
            <main className="flex-grow">{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
